- name: Install git
  apt: name=git state=latest

- name: Install Python pip
  apt: name=python-pip

- name: Install Python packages
  pip:
    name: "{{ item }}"
  with_items: "{{ python_packages }}"
