- name: Create ssh key pair for Jenkins
  user:
    name: jenkins
    generate_ssh_key: yes
    ssh_key_file: "{{ deploy_ssh_key_file }}"
  register: ssh_key_created

- name: Read SSH public key.
  command: "cat {{ deploy_ssh_key_file }}.pub"
  register: ssh_public_key

- name: Add SSH public key to GitHub repo
  uri:
    url: https://api.github.com/repos/Omenia/Tammer/keys
    method: POST
    status_code: 201
    body:
      read_only: true
      key: "{{ ssh_public_key.stdout }}"
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: "token {{ vault_github_token }}"
  when: ssh_key_created.changed
