- name: Restart Jenkins
  service: name=jenkins state=restarted

- name: Wait for Jenkins to come up
  uri:
    url: "{{ jenkins_address }}"
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
