instance_type: t2.micro
volume_size: 60
ami_name: debian-jessie-amd64-hvm-2016-02-17-ebs-*
target_aws_region: eu-west-1
number_of_instances: 1
ec2_access_key: "{{ ec2_access }}"
ec2_secret_key: "{{ ec2_secret }}"
security_group: ssh, http, https
ssh_key: "{{ vault_ssh_key }}"
tag: tammer-jenkins-master
group: tammer-jenkins-master
elastic_public_ip: "{{ vault_elastic_public_ip }}"
elastic_public_dns: "{{ vault_elastic_public_dns }}"
